# 服务器配置文件模板
base-info:
  name: My Engine Server
  ip-address: 0.0.0.0
  port: 8000
  web-directory: /web
  plugin-directory: /plugins

sqlite-log-db:
  enable: false
  location: log.db

file-log-dir:
  enable: true
  location: /log

thread-pool:
  name: ThreadPool
  threads: 16