file(GLOB_RECURSE MyEngineSrc "src/*.cpp" "src/*.h")
file(GLOB_RECURSE YamlCppSrc "thirdparty/yaml-cpp/src/*.cpp" "thirdparty/yaml-cpp/src/*.h")

if (UNIX)
    add_library(MyEngineLib ${MyEngineSrc} ${YamlCppSrc})
    set(THREADS_PREFER_PTHREAD_FLAG ON)
    find_package(Threads REQUIRED)
    target_link_libraries(MyEngineLib PUBLIC Threads::Threads)
endif ()

function(add_test exec_name src)
    add_executable(${exec_name} ${src})
    target_link_libraries(${exec_name} MyEngineLib)
endfunction(add_test)

add_test(TestTcpClient test/TestTcpClient/main.cpp)
add_test(TestTcpServer test/TestTcpServer/main.cpp)
add_test(TestHttpServer test/TestHttpServer/main.cpp)
add_test(TestHttpClient test/TestHttpClient/main.cpp)
add_test(TestServlet test/TestServlet/main.cpp)
add_test(TestApp test/TestApp/main.cpp)
add_test(TestThreadPool test/TestThreadPool/main.cpp)
add_test(TestLogger test/TestLogger/main.cpp)